MicroServices/src/ReportingHub/Pages/About.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ReportingHub.Pages
{
	public class AboutModel : PageModel
	{
		public string Message { get; set; }

		public void OnGet()
		{
			Message = "Your application description page.";
		}
	}
}

MicroServices/src/ReportingHub/Pages/Components/MainMenu/MainMenuViewComponent.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace ReportingHub.Pages.Components.MainMenu
{
	public class MainMenuViewComponent : ViewComponent
	{
		public Task<IViewComponentResult> InvokeAsync()
		{
			return Task.FromResult((IViewComponentResult)View());
		}
	}
}

MicroServices/src/ReportingHub/Pages/Contact.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ReportingHub.Pages
{
	public class ContactModel : PageModel
	{
		public string Message { get; set; }

		public void OnGet()
		{
			Message = "Your contact page.";
		}
	}
}

MicroServices/src/ReportingHub/Pages/Error.cshtml.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ReportingHub.Pages
{
	public class ErrorModel : PageModel
	{
		public string RequestId { get; set; }

		public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

		public void OnGet()
		{
			RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
		}
	}
}

MicroServices/src/ReportingHub/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ReportingHub.Pages
{
	public class IndexModel : PageModel
	{
		public void OnGet()
		{

		}
	}
}

MicroServices/src/ReportingHub/Pages/About.cshtml
@page
@model AboutModel
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@Model.Message</h3>

<p>Use this area to provide additional information.</p>

MicroServices/src/ReportingHub/Pages/Contact.cshtml
@page
@model ContactModel
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@Model.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

MicroServices/src/ReportingHub/Pages/Index.cshtml
@page
@model IndexModel
@{
	ViewData["Title"] = "Canonn Research Reporting Hub";
}
<div class="container">
	<h1>@ViewData["Title"]</h1>

	<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
		<ol class="carousel-indicators">
			<li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
			<li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
			<li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
		</ol>
		<div class="carousel-inner">
			<div class="carousel-item active">
				<img class="d-block w-100" src="~/Images/BrainTrees.jpg" alt="Brain Trees">
				<div class="carousel-caption" role="option">
					<div class="jumbotron-fluid">
						<div class="container">
							<h1 class="display-4">Report Brain Trees on the Canonn Reporting Hub</h1>
							<p class="lead"><a asp-page="/Report/BrainTree">We need your science!</a></p>
						</div>
					</div>
				</div>
			</div>
			<div class="carousel-item">
				<img class="d-block w-100" src="~/Images/FlamingFumerole.jpg" alt="Fumeroles">
				<div class="carousel-caption" role="option">
					<div class="jumbotron-fluid">
						<div class="container">
							<h1 class="display-4">Found some geological activities in space?</h1>
							<p class="lead"><a asp-page="/Report/Fumarole">Report your fumerols now!</a></p>
						</div>
					</div>
				</div>
			</div>
			<div class="carousel-item">
				<img class="d-block w-100" src="~/Images/Barnacles.jpg" alt="Barnacles">
				<div class="carousel-caption" role="option">
					<div class="jumbotron-fluid">
						<div class="container">
							<h1 class="display-4">Cut yourself on a space-crashed Crustacea?</h1>
							<p class="lead"><a asp-page="/Report/Barnacle">We'd love to know about your Barnacles!</a></p>
						</div>
					</div>
				</div>
			</div>
			<a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
				<span class="carousel-control-prev-icon" aria-hidden="true"></span>
				<span class="sr-only">Previous</span>
			</a>
			<a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
				<span class="carousel-control-next-icon" aria-hidden="true"></span>
				<span class="sr-only">Next</span>
			</a>


		</div>
	</div>
</div>

@*
	<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="6000">
		 <ol class="carousel-indicators">
			  <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
			  <li data-target="#myCarousel" data-slide-to="1"></li>
			  <li data-target="#myCarousel" data-slide-to="2"></li>
			  <li data-target="#myCarousel" data-slide-to="3"></li>
		 </ol>
		 <div class="carousel-inner" role="listbox">
			  <div class="item active">
					<img src="~/images/banner1.svg" alt="ASP.NET" class="img-responsive" />
					<div class="carousel-caption" role="option">
						 <p>
							  Learn how to build ASP.NET apps that can run anywhere.
							  <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525028&clcid=0x409">
									Learn More
							  </a>
						 </p>
					</div>
			  </div>
			  <div class="item">
					<img src="~/images/banner2.svg" alt="Visual Studio" class="img-responsive" />
					<div class="carousel-caption" role="option">
						 <p>
							  There are powerful new features in Visual Studio for building modern web apps.
							  <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525030&clcid=0x409">
									Learn More
							  </a>
						 </p>
					</div>
			  </div>
			  <div class="item">
					<img src="~/images/banner3.svg" alt="Package Management" class="img-responsive" />
					<div class="carousel-caption" role="option">
						 <p>
							  Bring in libraries from NuGet and npm, and automate tasks using Grunt or Gulp.
							  <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525029&clcid=0x409">
									Learn More
							  </a>
						 </p>
					</div>
			  </div>
			  <div class="item">
					<img src="~/images/banner4.svg" alt="Microsoft Azure" class="img-responsive" />
					<div class="carousel-caption" role="option">
						 <p>
							  Learn how Microsoft's Azure cloud platform allows you to build, deploy, and scale web apps.
							  <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525027&clcid=0x409">
									Learn More
							  </a>
						 </p>
					</div>
			  </div>
		 </div>
		 <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
			  <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
			  <span class="sr-only">Previous</span>
		 </a>
		 <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
			  <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
			  <span class="sr-only">Next</span>
		 </a>
	</div>

	<div class="row">
		 <div class="col-md-3">
			  <h2>Application uses</h2>
			  <ul>
					<li>Sample pages using ASP.NET Core Razor Pages</li>
					<li>Theming using <a href="https://go.microsoft.com/fwlink/?LinkID=398939">Bootstrap</a></li>
			  </ul>
		 </div>
		 <div class="col-md-3">
			  <h2>How to</h2>
			  <ul>
					<li><a href="https://go.microsoft.com/fwlink/?linkid=852130">Working with Razor Pages.</a></li>
					<li><a href="https://go.microsoft.com/fwlink/?LinkId=699315">Manage User Secrets using Secret Manager.</a></li>
					<li><a href="https://go.microsoft.com/fwlink/?LinkId=699316">Use logging to log a message.</a></li>
					<li><a href="https://go.microsoft.com/fwlink/?LinkId=699317">Add packages using NuGet.</a></li>
					<li><a href="https://go.microsoft.com/fwlink/?LinkId=699319">Target development, staging or production environment.</a></li>
			  </ul>
		 </div>
		 <div class="col-md-3">
			  <h2>Overview</h2>
			  <ul>
					<li><a href="https://go.microsoft.com/fwlink/?LinkId=518008">Conceptual overview of what is ASP.NET Core</a></li>
					<li><a href="https://go.microsoft.com/fwlink/?LinkId=699320">Fundamentals of ASP.NET Core such as Startup and middleware.</a></li>
					<li><a href="https://go.microsoft.com/fwlink/?LinkId=398602">Working with Data</a></li>
					<li><a href="https://go.microsoft.com/fwlink/?LinkId=398603">Security</a></li>
					<li><a href="https://go.microsoft.com/fwlink/?LinkID=699321">Client side development</a></li>
					<li><a href="https://go.microsoft.com/fwlink/?LinkID=699322">Develop on different platforms</a></li>
					<li><a href="https://go.microsoft.com/fwlink/?LinkID=699323">Read more on the documentation site</a></li>
			  </ul>
		 </div>
		 <div class="col-md-3">
			  <h2>Run &amp; Deploy</h2>
			  <ul>
					<li><a href="https://go.microsoft.com/fwlink/?LinkID=517851">Run your app</a></li>
					<li><a href="https://go.microsoft.com/fwlink/?LinkID=517853">Run tools such as EF migrations and more</a></li>
					<li><a href="https://go.microsoft.com/fwlink/?LinkID=398609">Publish to Microsoft Azure App Service</a></li>
			  </ul>
		 </div>
	</div>
*@

MicroServices/src/ReportingHub/Pages/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no" />

	<title>@ViewData["Title"] - ReportFormsSample</title>

	<environment include="Development">
		<link rel="stylesheet" href="~/css/bootstrap-theme.css" />
		<link rel="stylesheet" href="~/css/site.css" />
	</environment>
	<environment exclude="Development">
		<link rel="stylesheet" href="~/css/bootstrap-theme.min.css" asp-append-version="true" />
		<link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
	</environment>
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.css" integrity="sha256-NuCn4IvuZXdBaFKJOAcsU2Q3ZpwbdFisd5dux4jkQ5w=" crossorigin="anonymous" />
	<link href="https://fonts.googleapis.com/css?family=Michroma|Fira+Sans" rel="stylesheet">
</head>
<body>
<header>
	<vc:main-menu></vc:main-menu>
</header>

	<main class="container" role="main">
		@RenderBody()
	</main>

<footer class="footer bg-dark text-light">
	<div class="container d-flex justify-content-between">
		<span>&copy; @DateTime.UtcNow.Year - Canonn R&amp;D | <a href="https://canonn.science">https://canonn.sciene</a></span>
		<span>This project is on <a href="https://github.com/canonn-science/canonn-api"><i class="fa fa-lg fa-github"></i> GitHub</a></span>
	</div>
</footer>

<environment include="Development">
	<script src="~/lib/js/jquery.js"></script>
	<script src="~/lib/js/bootstrap.js"></script>
	<script src="~/lib/js/jquery.validate.js"></script>
	<script src="~/lib/js/jquery.validate.unobtrusive.js"></script>
	<script src="~/js/site.js" asp-append-version="true"></script>
</environment>
<environment exclude="Development">
	<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.slim.min.js"
				  asp-fallback-src="~/lib/jquery/dist/jquery-3.3.1.slim.min.js"
				  asp-fallback-test="window.jQuery"
				  crossorigin="anonymous"
				  integrity="sha256-3edrmyuQ0w65f8gfBsqowzjJe2iM6n0nKciPUp8y+7E=">
		</script>
@*	<script src="~/lib/js/jquery.min.js" asp-append-version="true"></script>*@
	<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0/js/bootstrap.min.js"
			  asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
			  asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
			  crossorigin="anonymous"
			  integrity="sha256-5+02zu5UULQkO7w1GIr6vftCgMfFdZcAHeDtFnKZsBs=">
	</script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.17.0/jquery.validate.min.js"
			  asp-fallback-src="~/lib/js/jquery.validate.min.js"
			  asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.validate"
			  crossorigin="anonymous"
			  integrity="sha256-F6h55Qw6sweK+t7SiOJX+2bpSAa3b/fnlrVCJvmEj1A=">
	</script>
	<script src="~/lib/js/jquery.validate.unobtrusive.min.js" asp-append-version="true"></script>
	<script src="~/js/site.min.js" asp-append-version="true"></script>
</environment>
	<script src="~/Scripts/FormFactory/FormFactory.js" type="text/javascript"></script>
	@RenderSection("Scripts", required: false)
</body>
</html>